#!/bin/bash
set -e
set -x

REPO="https://api.github.com/repos/rancher/rke/actions/workflows/git-actions-go-generate.yml/dispatches"

case $GITHUB_REF_NAME in
  dev-v2.9|release-v2.9)
    ACTION_TARGET_BRANCH="release/v1.6"
    ;;
  *)
    echo "Not a valid branch, not dispatching event"
    exit 0
esac

echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
echo "GITHUB_ACTOR: $GITHUB_ACTOR"

echo "Dispatching to branch ${ACTION_TARGET_BRANCH}"

# send dispatch event to workflow
curl -XPOST -u "${PAT_USERNAME}:${PAT_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json"  \
        -H "Content-Type: application/json" $REPO \
        --data '{"ref": "'"$ACTION_TARGET_BRANCH"'","inputs":{"source_author":"'"$GITHUB_ACTOR"'"}}'
